theme: jekyll-theme-minimal
title: Sudipta Dutta
description: I am a software engineer and student currently living in Munich, Germany. My interests range from technology to photography. I am also interested in travel, football, and astronomy.
logo: https://avatars0.githubusercontent.com/u/907075?s=400&u=91bc99849773cd631d745c4b90c4ae553ef23855&v=4
show_downloads: "false"
google_analytics: xxx
