theme: jekyll-theme-minimal
title: Sudipta Dutta
description: I am a software engineer and student currently living in Munich, Germany. My interests range from technology to photography. I am also interested in travel, football, and astronomy.
logo: https://avatars.githubusercontent.com/u/907075?v=4
show_downloads: false
