theme: jekyll-theme-minimal
title: Sudipta Dutta
description: I am a software engineer and student currently living in Munich, Germany. My interests range from technology to photography. I am also interested in travel, football, and astronomy.
logo: https://bit.ly/3nTla39
show_downloads: false
