theme: jekyll-theme-minimal
title: Sudipta Dutta
description: I am a software engineer and student currently living in Munich, Germany. My interests range from technology to photography. I am also interested in travel, football, and astronomy. ![Github stats](https://github-readme-stats.vercel.app/api?username=ir2pid&show_icons=true&count_private=true&include_all_commits=true)[![Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=ir2pid)](https://github.com/anuraghazra/github-readme-stats)
logo: https://bit.ly/3nTla39
show_downloads: false
