theme: jekyll-theme-minimal
title: Sudipta Dutta
description: A strategy consulting professional with a commercial mind-set. 
logo: https://i.stack.imgur.com/AIvqN.png?s=328&g=1
show_downloads: "false"
google_analytics: xxx
