theme: jekyll-theme-minimal
title: Sudipta Dutta
description: A strategy consulting professional with a commercial mind-set. 
logo: https://github.com/suchidey/Resume/blob/master/suchi/suchiDp.jpg?raw=true
show_downloads: "false"
google_analytics: xxx
